name: Transform

on: [push, pull_request]

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache ontop
        uses: actions/cache@v4
        env:
          cache-name: cache-mix-deps
        with:
          path: ./ontop-scripts/ontop
          key: ${{ runner.os }}-deps-${{ env.cache-name }}-${{ hashFiles('./ontop-scripts/convert.sh') }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ env.cache-name }}-
            ${{ runner.os }}-deps-
            ${{ runner.os }}-
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: triples.nt
          path: ontop-scripts/triples.nt
